name: farisfilm
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  http: 1.2.2                # Versi terbaru http untuk memanggil API
  provider: ^6.1.2           # Untuk state management sederhana (opsional)
  cached_network_image: ^3.2.3 # Untuk caching gambar dari API
  flutter_spinkit: ^5.2.1      # Untuk animasi loading
  google_fonts: ^6.2.1         # Untuk font kustom
  flutter_cors: ^1.5.0         # Untuk mengatasi CORS di Flutter web (opsional)
  carousel_slider: ^5.0.0
  path_provider: ^2.1.5
  # share_plus: ^10.1.2 # Add this line

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/           # Menyertakan direktori assets/images untuk gambar

  fonts:
    - family: Poppins           # Menambahkan font Poppins ke aplikasi
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
